apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: command-app
  name: command-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: command-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: command-app
    spec:
      containers:
      - image: quay.io/navdeep_sachdeva/custom_httpd:1.0
        name: custom-httpd-p8g2g
        ports:
        - containerPort: 8080
        - containerPort: 8443

      - image: docker.io/library/mysql
        name: db
        ports:
          - containerPort: 3306
